# Generated by Django 5.2 on 2025-05-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medecin',
            options={'verbose_name': 'Médecin', 'verbose_name_plural': 'Médecins'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='role',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='genre',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1),
        ),
    ]
