# Generated by Django 5.1.8 on 2025-05-27 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_medecin_options_alter_patient_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossiermedical',
            name='consultation',
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='consultations',
            field=models.ManyToManyField(to='core.consultation'),
        ),
    ]
