# Generated by Django 5.1.8 on 2025-05-27 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_dossiermedical_consultation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiermedical',
            name='patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.patient'),
        ),
    ]
